AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
    Max: 20
Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UnknownEnv:
  Environments:
  - production
  - development
  - test

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
